[tools]
node = 'lts'
python = ['3.12','3.13','miniconda3-latest']
ruby = ['3.4']
java = ['temurin-17','temurin-21']
golang = ['1.24']
maven = ['3.9.9']
gradle = ['8.13']
rust = ['stable']
sbt = ['1.10']

[settings]
env_file = '.env'
