[tools]
node = 'lts'
python = ['3.12', 'miniconda3-latest']
ruby = ['3.4.1']
java = ['temurin-17.0.13+11']
golang = ['1.23.5']
maven = ['3.9.9']
gradle = ['8.12']
rust = ['stable']
sbt = ['1.10.7']

[settings]
env_file = '.env'
