# `sheldon` configuration file
# ----------------------------
#
# See the documentation for more https://github.com/rossmacarthur/sheldon#readme

[templates]
defer = "{% for file in files %}zsh-defer source \"{{ file }}\"\n{% endfor %}"

[plugins.zsh-defer]
github = "romkatv/zsh-defer"

# Sourced
[plugins.zsh-completions]
github = "zsh-users/zsh-completions"
apply = [ "defer" ]

[plugins.base16]
github = "chriskempson/base16-shell"
apply = [ "defer" ]

[plugins.zsh-autocomplete]
github = "marlonrichert/zsh-autocomplete"
apply = [ "defer" ]

[plugins.zsh-autosuggestions]
github = "zsh-users/zsh-autosuggestions"
apply = ["defer"]

[plugins.fast-syntax-highlighting]
github = "zdharma-continuum/fast-syntax-highlighting"
apply = ["defer"]
