general.import = [
  "./catppuccin-mocha.toml"
]

[font]
size = 11.5

  [font.normal]
  family = "Berkeley Mono Variable"

[window]
opacity = 0.95

  [window.padding]
  x = 10
  y = 10

[cursor]
unfocused_hollow = false
thickness = 0.2

  [cursor.style]
  shape = "Underline"
  blinking = "Always"

[terminal]
  [terminal.shell]
  program = "C:/Users/Ben/scoop/shims/pwsh.exe"
  # program = "wsl"

[scrolling]
history = 100000
