#!/bin/bash
# load all shell config files
if [ -d "${HOME}/.config/shrc" ]; then
    for file in "${HOME}/.config/shrc"/*(N); do
        # shellcheck source=/dev/null
        . "$file"
    done
fi

# load all zsh config files
if [ -d "${HOME}/.config/zshrc" ]; then
    for file in "${HOME}/.config/zshrc"/*(N); do
        # shellcheck source=/dev/null
        . "$file"
    done
fi
