#!/bin/bash
ln -sf $HOME/.dotfiles/vscode/settings.json "$HOME/Library/Application Support/Code/User/settings.json"
ln -sf $HOME/.dotfiles/vscode/keybindings.json "$HOME/Library/Application Support/Code/User/keybindings.json"
ln -sf $HOME/.dotfiles/vscode/snipppets "$HOME/Library/Application Support/Code/User/snipppets"