#!/bin/bash
#
# replace ssh agent with gpg-agent:

# - unload ssh agent
sudo launchctl unload -w /System/Library/LaunchAgents/com.openssh.ssh-agent.plist

# - gpg-agent is already managed by gpgtools, we only need to export ssh_auth_sock variables to the system
ln -sf $HOME/.dotfiles/yubikey/consulting.cochez.yubikey-ssh-support.plist "$HOME/Library/LaunchAgents/"
launchctl load  ~/Library/LaunchAgents/consulting.cochez.yubikey-ssh-support.plist
