# `sheldon` configuration file
# ----------------------------
#
# See the documentation for more https://github.com/rossmacarthur/sheldon#readme

shell = "zsh"

# defer setup: apply by default
apply = ["defer"]

[plugins.zsh-defer]
github = "romkatv/zsh-defer"
apply = ["source"]

[templates]
defer = "{% for file in files %}zsh-defer source \"{{ file }}\"\n{% endfor %}"

# plugins
[plugins.conda-zsh-completion]
github = "esc/conda-zsh-completion"

[plugins.zsh-completions]
github = "zsh-users/zsh-completions"

[plugins.zsh-autocomplete]
github = "marlonrichert/zsh-autocomplete"

[plugins.zsh-autosuggestions]
github = "zsh-users/zsh-autosuggestions"
use = ["{{ name }}.zsh"]

[plugins.base16]
github = "chriskempson/base16-shell"

[plugins.fast-syntax-highlighting]
github = "zdharma-continuum/fast-syntax-highlighting"

[plugins.compinit]
inline = 'autoload -Uz compinit && zsh-defer compinit'
