#!/bin/bash
# load all shell config files
if [ -d "${HOME}/.config/shrc" ]; then
    for file in "${HOME}/.config/shrc"/*; do
        # shellcheck source=/dev/null
        . "$file"
    done
fi

if [ -d "${HOME}/.config/bashrc" ]; then
    for file in "${HOME}/.config/bashrc"/*; do
        # shellcheck source=/dev/null
        . "$file"
    done
fi
