[font]
size = 10

  [font.normal]
  family = "MonoLisa Nerd Font"
  style = "Light Regular"

[window]
opacity = 0.95

  [window.padding]
  x = 8
  y = 8

[cursor]
unfocused_hollow = false
thickness = 0.2

  [cursor.style]
  shape = "Underline"
  blinking = "Always"

[shell]
program = "C:/Users/Ben/scoop/shims/pwsh.exe"
# program = "wsl"

[scrolling]
history = 100000
