[font]
size = 10

  [font.normal]
  family = "MonoLisa Nerd Font"

[window]
opacity = 0.85
blur = true

  [window.padding]
  x = 10
  y = 10

[cursor]
unfocused_hollow = false
thickness = 0.2

  [cursor.style]
  shape = "Underline"
  blinking = "Always"

[shell]
program = "C:/Program Files/PowerShell/7/pwsh.exe"
# program = "wsl"

[scrolling]
history = 10000
