tap "homebrew/bundle"
tap "homebrew/cask"
tap "homebrew/cask-drivers"
tap "homebrew/cask-fonts"
tap "homebrew/cask-versions"
tap "homebrew/command-not-found"
tap "homebrew/core"
tap "homebrew/services"
tap "thoughtbot/formulae"
brew "aria2"
brew "readline"
brew "python"
brew "awscli"
brew "bash"
brew "gettext", link: true
brew "ccat"
brew "coreutils"
brew "dbus"
brew "dpkg"
brew "duti"
brew "exa"
brew "exiftool"
brew "ffmpeg", args: ["HEAD"]
brew "fzf"
brew "git"
brew "gnu-sed"
brew "gradle-completion"
brew "graphviz"
brew "highlight"
brew "hopenpgp-tools"
brew "hub"
brew "hugo"
brew "jenv"
brew "jq"
brew "jsonpp"
brew "kompose"
brew "libdvdcss"
brew "libpq"
brew "libu2f-host"
brew "libusb"
brew "m-cli"
brew "mas"
brew "youtube-dl"
brew "mpv", args: ["HEAD"]
brew "mtr"
brew "nmap"
brew "nnn"
brew "openssl"
brew "pandoc"
brew "pipenv"
brew "poppler"
brew "python@2"
brew "qpdf"
brew "ruby-build"
brew "rbenv"
brew "ripgrep"
brew "rust"
brew "sbt"
brew "ssh-copy-id"
brew "stern"
brew "swig"
brew "telnet"
brew "terminal-notifier"
brew "the_silver_searcher"
brew "thefuck"
brew "tldr"
brew "v8@3.15", link: true
brew "wget"
brew "wireguard-tools"
brew "ykpers"
brew "yubico-piv-tool"
brew "z"
brew "zplug"
brew "zsh"
brew "zsh-completions"
brew "thoughtbot/formulae/rcm"
cask "1password"
cask "adobe-acrobat-reader"
cask "airfoil"
cask "alfred"
cask "appcleaner"
cask "arduino"
cask "audio-hijack"
cask "bartender"
cask "bbedit"
cask "beoplay-software-update"
cask "betterzip"
cask "calibre"
cask "chatmate-for-facebook"
cask "chatmate-for-whatsapp"
cask "choosy"
cask "chromium"
cask "cursorsense"
cask "daisydisk"
cask "dash"
cask "devonthink"
cask "disk-sensei"
cask "docker-edge"
cask "dropbox"
cask "dropzone"
cask "duet"
cask "fantastical"
cask "firefox"
cask "fission"
cask "flux"
cask "font-hasklig"
cask "garmin-basecamp"
cask "garmin-express"
cask "google-backup-and-sync"
cask "gpg-suite-no-mail"
cask "handbrake"
cask "hazel"
cask "iina"
cask "istat-menus"
cask "iterm2"
cask "jetbrains-toolbox"
cask "kaleidoscope"
cask "karabiner-elements"
cask "keybase"
cask "keyboard-maestro"
cask "kitematic"
cask "launchcontrol"
cask "loopback"
cask "marked"
cask "mattermost"
cask "omnifocus"
cask "omnigraffle"
cask "omnioutliner"
cask "pacifist"
cask "paw"
cask "pdf-expert"
cask "phantomjs"
cask "postico"
cask "power-manager"
cask "resolutionator"
cask "screenflow"
cask "screens"
cask "screens-connect"
cask "script-debugger"
cask "sdformatter"
cask "setapp"
cask "skype"
cask "slack-beta"
cask "soulver"
cask "soundsource"
cask "spamsieve"
cask "spotify"
cask "steermouse"
cask "transmit"
cask "turbo-boost-switcher"
cask "vagrant"
cask "vagrant-vmware-utility"
cask "visual-studio-code"
cask "vitamin-r"
cask "vlc"
cask "vmware-fusion"
cask "wwdc"
cask "xerox-print-driver"
cask "xscope"
cask "yubico-authenticator"
mas "Affinity Designer", id: 824171161
mas "Affinity Photo", id: 824183456
mas "Amphetamine", id: 937984704
mas "Better", id: 1121192229
mas "Better Rename 10", id: 1063663640
mas "CARROT Weather", id: 993487541
mas "Day One", id: 1055511498
mas "Deliveries", id: 924726344
mas "djay Pro", id: 1302002064
mas "Expressions", id: 913158085
mas "File Multi Tool 6", id: 1194004025
mas "Finances", id: 1218241304
mas "FineReader OCR Pro", id: 687301476
mas "Formatter", id: 1190228172
mas "GAget", id: 968487158
mas "Gemini 2", id: 1090488118
mas "iFlicks 2", id: 731062389
mas "iMazing HEIC Converter", id: 1292198261
mas "Irvue", id: 1039633667
mas "ISOBMFF Explorer", id: 1300778278
mas "JSON Helper", id: 453114608
mas "Micro Snitch", id: 972028355
mas "Microsoft Excel", id: 462058435
mas "Microsoft PowerPoint", id: 462062816
mas "Microsoft Remote Desktop", id: 1295203466
mas "Microsoft Word", id: 462054704
mas "Mimeo Photos", id: 1282504627
mas "Paprika Recipe Manager 3", id: 1303222628
mas "Parcel", id: 639968404
mas "PCalc", id: 403504866
mas "PopClip", id: 445189367
mas "Reeder", id: 1449412482
mas "SnippetsLab", id: 1006087419
mas "SubEthaEdit", id: 728530824
mas "Textual IRC Client", id: 1262957439
mas "ToothFairy", id: 1191449274
mas "Tweetbot", id: 1384080005
mas "WiFi Explorer", id: 494803304
mas "WiFi Signal", id: 525912054
mas "Yoink", id: 457622435
