tap "thoughtbot/formulae"
tap "homebrew/command-not-found"
tap "homebrew/core"
tap "homebrew/versions"
tap "homebrew/bundle"
tap "homebrew/services"
tap "caskroom/drivers"
tap "caskroom/fonts"
tap "caskroom/versions"
tap "caskroom/cask"
tap "caskroom/eid"
cask "java"
cask "caskroom/versions/java8"
brew "openssl"
brew "readline"
brew "python3"
brew "awscli"
brew "ccat"
brew "coreutils"
brew "dbus", restart_service: true
brew "docker-completion"
brew "docker-compose-completion"
brew "docker-machine-completion"
brew "dpkg"
brew "exa"
brew "fzf"
brew "git"
brew "gnu-sed"
brew "gradle"
brew "gradle-completion"
brew "highlight"
brew "hopenpgp-tools"
brew "hub"
brew "hugo"
brew "infer"
brew "jenv"
brew "jq"
brew "jsonpp"
brew "libu2f-host"
brew "libusb"
brew "m-cli"
brew "mas"
brew "maven"
brew "monkeysphere"
brew "mpv"
brew "n"
brew "nmap"
brew "phantomjs"
brew "poppler"
brew "python"
brew "qpdf"
brew "ruby-build"
brew "rbenv"
brew "ripgrep"
brew "sbt"
brew "ssh-copy-id"
brew "swig"
brew "telnet"
brew "terminal-notifier"
brew "the_silver_searcher"
brew "thefuck"
brew "tldr"
brew "v8@3.15", link: true
brew "wget"
brew "ykpers"
brew "yubico-piv-tool", link: false
brew "zplug"
brew "zsh"
brew "zsh-completions"
brew "thoughtbot/formulae/rcm"
cask "1password"
cask "adobe-acrobat-reader"
cask "aerial"
cask "airfoil"
cask "appcleaner"
cask "arq"
cask "audio-hijack"
cask "bartender"
cask "bbedit"
cask "beoplay-software-update"
cask "bettertouchtool"
cask "betterzip"
cask "beyond-compare"
cask "caprine"
cask "carbon-copy-cloner"
cask "chatmate-for-facebook"
cask "chatmate-for-whatsapp"
cask "coconutbattery"
cask "cycling74-max"
cask "daisydisk"
cask "dash"
cask "debookee"
cask "devonthink-pro-office"
cask "disk-sensei"
cask "docker"
cask "dropbox"
cask "droplr"
cask "dropzone"
cask "fantastical"
cask "firefox"
cask "fission"
cask "focus"
cask "google-chrome"
cask "gotomeeting"
cask "gpgtools"
cask "hazel"
cask "hipchat"
cask "houdahspot"
cask "iina"
cask "intel-power-gadget"
cask "istat-menus"
cask "iterm2"
cask "jetbrains-toolbox"
cask "jprofiler"
cask "kap"
cask "keybase"
cask "keyboard-maestro"
cask "kitematic"
cask "launchbar"
cask "launchcontrol"
cask "little-snitch"
cask "loopback"
cask "marked"
cask "microsoft-office"
cask "omnifocus"
cask "omnigraffle"
cask "omnioutliner"
cask "pacifist"
cask "paragon-ntfs"
cask "paw"
cask "pdfexpert"
cask "postgres"
cask "power-manager"
cask "resolutionator"
cask "rocket"
cask "screens"
cask "shimo"
cask "simplifyextras"
cask "skype"
cask "soulver"
cask "soundsource"
cask "spotify"
cask "stride"
cask "surge"
cask "teamviewer"
cask "timing"
cask "totals"
cask "tower"
cask "transmit"
cask "viscosity"
cask "visual-studio-code"
cask "vmware-fusion"
cask "witch"
cask "wwdc"
cask "yubikey-manager"
cask "yubikey-personalization-gui"
cask "yubikey-piv-manager"
cask "caskroom/drivers/logitech-options"
cask "caskroom/drivers/xerox-print-driver"
cask "caskroom/drivers/yubico-authenticator"
cask "caskroom/eid/eid-be"
cask "caskroom/eid/eid-be-viewer"
cask "caskroom/fonts/font-hasklig"
cask "caskroom/fonts/font-source-code-pro"
mas "Affinity Designer", id: 824171161
mas "Affinity Photo", id: 824183456
mas "Amphetamine", id: 937984704
mas "Better", id: 1121192229
mas "Better Rename 10", id: 1063663640
mas "Browser Fairy", id: 483014855
mas "Day One", id: 1055511498
mas "Deliveries", id: 924726344
mas "djay Pro 2", id: 1302002064
mas "File Multi Tool 6", id: 1194004025
mas "FineReader OCR Pro", id: 687301476
mas "Forecast Bar", id: 982710545
mas "Formatter", id: 1190228172
mas "GAget", id: 968487158
mas "Garmin BaseCamp", id: 411052274
mas "iFlicks 2", id: 731062389
mas "Irvue", id: 1039633667
mas "JSON Helper", id: 453114608
mas "Marked 2", id: 890031187
mas "MindNode", id: 1289197285
mas "Napkin", id: 581789185
mas "Paprika Recipe Manager 3", id: 1303222628
mas "Parcel", id: 639968404
mas "PCalc", id: 403504866
mas "PopClip", id: 445189367
mas "Reeder", id: 880001334
mas "ScanSnap Cloud", id: 1170434079
mas "Server", id: 883878097
mas "Shazam", id: 897118787
mas "Simplify", id: 448003584
mas "Slack", id: 803453959
mas "SnippetsLab", id: 1006087419
mas "Translate Tab", id: 458887729
mas "Tweetbot", id: 557168941
mas "Universal Document Viewer Pro", id: 895496813
mas "WiFi Explorer", id: 494803304
mas "WiFi Signal", id: 525912054
mas "Xcode", id: 497799835
