ZSHA_BASE=$HOME/.zsh-antigen
source $ZSHA_BASE/antigen/antigen.zsh

antigen-use oh-my-zsh
antigen-bundle git
antigen bundle npm
antigen bundle nvm
antigen bundle z
antigen bundle aws
antigen bundle mvn
antigen bundle command-not-found

if [ "$OSTYPE"="darwin11.0" ]; then
  antigen-bundle osx
  antigen-bundle bgnotify
  antigen bundle marked2
  antigen bundle xcode
fi

antigen-bundle zsh-users/zsh-history-substring-search
antigen bundle zsh-users/zsh-completions src
antigen-bundle zsh-users/zsh-syntax-highlighting

# antigen bundle akoenig/gulp.plugin.zsh
# antigen bundle akoenig/npm-run.plugin.zsh

antigen theme sorin
# antigen theme https://github.com/caiogondim/bullet-train-oh-my-zsh-theme bullet-train

antigen-apply

export PATH=/usr/local/bin:/Applications/Postgres.app/Contents/Versions/9.5/bin:$PATH
export EDITOR=subl

# use maven color output
alias mvn="mvn-color"

# rbenv
if [ -d $HOME/.rbenv ]; then
  eval "$(rbenv init -)"
fi

# link up with iterm2
test -e ${HOME}/.iterm2_shell_integration.zsh && source ${HOME}/.iterm2_shell_integration.zsh
