[font]
size = 14

  [font.normal]
  family = "MonoLisa Nerd Font"

[window]
opacity = 0.85
blur = true
decorations = "buttonless"

[cursor]
unfocused_hollow = false
thickness = 0.2

  [cursor.style]
  shape = "Underline"
  blinking = "Always"
