[font]
size = 14

  [font.normal]
  family = "MonoLisa Nerd Font"
  style = "Light Regular"

[window]
opacity = 0.95
decorations = "transparent"

  [window.padding]
  x = 8
  y = 25

[cursor]
unfocused_hollow = false
thickness = 0.2

  [cursor.style]
  shape = "Underline"
  blinking = "Always"

[scrolling]
history = 100000
